package modelo;
// Generated 14 ene 2026, 8:32:20 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ciclos generated by hbm2java
 */
public class Ciclos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nombre;
	private Set<Modulos> modulos = new HashSet<Modulos>(0);
	private Set<Matriculaciones> matriculaciones = new HashSet<Matriculaciones>(0);

	public Ciclos() {
	}

	public Ciclos(String nombre) {
		this.nombre = nombre;
	}

	public Ciclos(String nombre, Set<Modulos> modulos, Set<Matriculaciones> matriculaciones) {
		this.nombre = nombre;
		this.modulos = modulos;
		this.matriculaciones = matriculaciones;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Modulos> getModuloses() {
		return this.modulos;
	}

	public void setModuloses(Set<Modulos> moduloses) {
		this.modulos = moduloses;
	}

	public Set<Matriculaciones> getMatriculacioneses() {
		return this.matriculaciones;
	}

	public void setMatriculacioneses(Set<Matriculaciones> matriculacioneses) {
		this.matriculaciones = matriculacioneses;
	}

}
