package modelo;
// Generated 8 ene 2026, 12:35:34 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Ciclos generated by hbm2java
 */
public class Ciclos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String nombre;
	private Set<Modulos> moduloses = new HashSet<>(0);
	private Set<Matriculaciones>matriculacioneses = new HashSet<>(0);

	public Ciclos() {
	}

	public Ciclos(String nombre) {
		this.nombre = nombre;
	}

	public Ciclos(String nombre, Set<Modulos>moduloses, Set<Matriculaciones>matriculacioneses) {
		this.nombre = nombre;
		this.moduloses = moduloses;
		this.matriculacioneses = matriculacioneses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<Modulos> getModuloses() {
		return this.moduloses;
	}

	public void setModuloses(Set<Modulos> moduloses) {
		this.moduloses = moduloses;
	}

	public Set<Matriculaciones>getMatriculacioneses() {
		return this.matriculacioneses;
	}

	public void setMatriculacioneses(Set<Matriculaciones>matriculacioneses) {
		this.matriculacioneses = matriculacioneses;
	}

}
