package com.example.ProyectoSpringboot.modelo;
// Generated 14 ene 2026, 8:32:20 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Modulos generated by hbm2java
 */
public class Modulos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	@JsonIgnore
	private Ciclos ciclos;
	private String nombre;
	private String nombreEus;
	private int horas;
	private byte curso;
	private Set<Horarios> horarios = new HashSet<Horarios>(0);

	public Modulos() {
	}

	public Modulos(Ciclos ciclos, String nombre, int horas, byte curso) {
		this.ciclos = ciclos;
		this.nombre = nombre;
		this.horas = horas;
		this.curso = curso;
	}

	public Modulos(Ciclos ciclos, String nombre, String nombreEus, int horas, byte curso, Set<Horarios>horarios) {
		this.ciclos = ciclos;
		this.nombre = nombre;
		this.nombreEus = nombreEus;
		this.horas = horas;
		this.curso = curso;
		this.horarios = horarios;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Ciclos getCiclos() {
		return this.ciclos;
	}

	public void setCiclos(Ciclos ciclos) {
		this.ciclos = ciclos;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getNombreEus() {
		return this.nombreEus;
	}

	public void setNombreEus(String nombreEus) {
		this.nombreEus = nombreEus;
	}

	public int getHoras() {
		return this.horas;
	}

	public void setHoras(int horas) {
		this.horas = horas;
	}

	public byte getCurso() {
		return this.curso;
	}

	public void setCurso(byte curso) {
		this.curso = curso;
	}

	public Set<Horarios> getHorarios() {
		return this.horarios;
	}

	public void setHorarios(Set<Horarios> horarios) {
		this.horarios = horarios;
	}

}
