package com.example.ProyectoSpringboot.modelo;
// Generated 14 ene 2026, 8:32:20 by Hibernate Tools 6.5.1.Final

import java.util.HashSet;
import java.util.Set;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;


/**
 * Tipos generated by hbm2java
 */

@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"}) //Si no añado esto me dan errores
public class Tipos implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Integer id;
	private String name;
	private String nameEu;
	@JsonIgnore
	private Set<Users> users = new HashSet<Users>(0);

	public Tipos() {
	}

	public Tipos(String name) {
		this.name = name;
	}

	public Tipos(String name, String nameEu, Set<Users> userses) {
		this.name = name;
		this.nameEu = nameEu;
		this.users = userses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getNameEu() {
		return this.nameEu;
	}

	public void setNameEu(String nameEu) {
		this.nameEu = nameEu;
	}

	public Set<Users> getUsers() {
		return this.users;
	}

	public void setUsers(Set<Users> users) {
		this.users = users;
	}

}
